version: '3.8'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - "4000:4000"     # Cube.dev web UI and REST API
      - "15432:15432"   # SQL API (PostgreSQL compatible)
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_API_SECRET=demo-secret-key-12345
      - CUBEJS_CACHE_AND_QUEUE_DRIVER=memory
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=172.19.215.172
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=ecommerce_db
      - CUBEJS_DB_USER=admin
      - CUBEJS_DB_PASS=admin123
      - CUBEJS_DB_SCHEMA=ecommerce
      - CUBEJS_WEB_SOCKETS=true
      # SQL API Configuration
      - CUBEJS_PG_SQL_PORT=15432
      - CUBEJS_SQL_USER=cube
      - CUBEJS_SQL_PASSWORD=password
      # Additional settings
      - CUBEJS_SCHEMA_PATH=model
    volumes:
      - ./model:/cube/conf/model:ro
      - ./package.json:/cube/conf/package.json:ro
    restart: unless-stopped