cubes:
- name: product_category_name_translations
  sql_table: ecommerce.product_category_name_translations
  description: This data cube represents translated product category names in English
    for an ecommerce platform, facilitating cross-language analysis and decision-making
    for product categorization and marketing strategies.
  measures:
  - name: count
    type: count
    description: count → "Total number of records in product category translations
      table"
  - name: count_distinct
    sql: product_category_name
    type: count_distinct
    description: count_distinct → "Number of unique product categories in translations
      table"
  dimensions:
  - name: product_category_name
    sql: product_category_name
    type: string
    description: '"Translated product category name"'
    primary_key: true
  - name: product_category_name_english
    sql: product_category_name_english
    type: string
    description: '"English translation of product category name"'
