cubes:
- name: products
  sql_table: ecommerce.products
  description: The "products" data cube in the ecommerce database represents essential
    product attributes such as category, dimensions, weight, and description length,
    enabling analysis for optimizing product offerings and enhancing customer shopping
    experiences.
  measures:
  - name: count
    type: count
    description: count → "Total number of records in the products table"
  - name: count_distinct
    sql: product_id
    type: count_distinct
    description: count_distinct_product_id → "Total unique products in inventory"
  - name: sum_product_name_length
    sql: product_name_length
    type: sum
    description: Total length of product names in characters for all products in the
      dataset.
  - name: avg_product_name_length
    sql: product_name_length
    type: avg
    description: '"Average length of product names in characters."'
  - name: min_product_name_length
    sql: product_name_length
    type: min
    description: min_product_name_length → "Shortest length of product names in characters"
  - name: max_product_name_length
    sql: product_name_length
    type: max
    description: max_product_name_length → "Maximum length of product names in characters"
  - name: sum_description_length
    sql: description_length
    type: sum
    description: '"Total length of product descriptions in characters"'
  - name: avg_description_length
    sql: description_length
    type: avg
    description: '"Average length of product descriptions in characters."'
  - name: min_description_length
    sql: description_length
    type: min
    description: min_description_length → "Minimum length of product descriptions
      in characters"
  - name: max_description_length
    sql: description_length
    type: max
    description: max_description_length → "Maximum length of product descriptions
      in characters"
  - name: sum_product_photos_qty
    sql: product_photos_qty
    type: sum
    description: Total number of product photos uploaded.
  - name: avg_product_photos_qty
    sql: product_photos_qty
    type: avg
    description: Average number of photos per product in the product catalog.
  - name: min_product_photos_qty
    sql: product_photos_qty
    type: min
    description: '"Minimum number of photos for each product in the dataset."'
  - name: max_product_photos_qty
    sql: product_photos_qty
    type: max
    description: 'max_product_photos_qty: "Maximum number of photos per product in
      the dataset."'
  - name: sum_product_weight_g
    sql: product_weight_g
    type: sum
    description: Total weight of all products sold in grams.
  - name: avg_product_weight_g
    sql: product_weight_g
    type: avg
    description: '"Average weight of products in grams sold."'
  - name: min_product_weight_g
    sql: product_weight_g
    type: min
    description: '"Minimum weight of products in grams sold."'
  - name: max_product_weight_g
    sql: product_weight_g
    type: max
    description: max_product_weight_g → "Maximum weight of products in grams"
  - name: sum_product_lenght_cm
    sql: product_lenght_cm
    type: sum
    description: '"Total length of all products in centimeters"'
  - name: avg_product_lenght_cm
    sql: product_lenght_cm
    type: avg
    description: Average length of products in centimeters.
  - name: min_product_lenght_cm
    sql: product_lenght_cm
    type: min
    description: '"Minimum length of products in centimeters in the dataset."'
  - name: max_product_lenght_cm
    sql: product_lenght_cm
    type: max
    description: '"Maximum length of products in centimeters in the default domain."'
  - name: sum_product_height_cm
    sql: product_height_cm
    type: sum
    description: Total height of all products in centimeters.
  - name: avg_product_height_cm
    sql: product_height_cm
    type: avg
    description: Average height of products in centimeters.
  - name: min_product_height_cm
    sql: product_height_cm
    type: min
    description: '"Minimum height of products in centimeters in the dataset."'
  - name: max_product_height_cm
    sql: product_height_cm
    type: max
    description: max_product_height_cm → "Maximum height of products in centimeters"
  - name: sum_product_width_cm
    sql: product_width_cm
    type: sum
    description: Total width of products in centimeters.
  - name: avg_product_width_cm
    sql: product_width_cm
    type: avg
    description: Average width of products in centimeters.
  - name: min_product_width_cm
    sql: product_width_cm
    type: min
    description: '"Minimum width of products in centimeters in the default domain."'
  - name: max_product_width_cm
    sql: product_width_cm
    type: max
    description: '"Maximum width of products in centimeters in default domain."'
  dimensions:
  - name: product_id
    sql: product_id
    type: string
    description: '"Unique product identifier"'
    primary_key: true
  - name: product_category_name
    sql: product_category_name
    type: string
    description: Product category classification for each product.
  - name: product_name_length
    sql: product_name_length
    type: number
    description: Length of product name.
  - name: description_length
    sql: description_length
    type: number
    description: '"Length of product description in characters"'
  - name: product_photos_qty
    sql: product_photos_qty
    type: number
    description: '"Number of photos for a product listing"'
  - name: product_weight_g
    sql: product_weight_g
    type: number
    description: '"Weight of product in grams"'
  - name: product_lenght_cm
    sql: product_lenght_cm
    type: number
    description: '"Product length in centimeters"'
  - name: product_height_cm
    sql: product_height_cm
    type: number
    description: '"Height measurement of a product in centimeters"'
  - name: product_width_cm
    sql: product_width_cm
    type: number
    description: '"Width measurement of a product in centimeters"'
