cubes:
- name: product_category_name_translations
  sql_table: ecommerce.product_category_name_translations
  description: Data cube for Product Category Name Translations analysis
  measures:
  - name: count
    type: count
    description: Total number of records
  - name: count_distinct
    sql: product_category_name
    type: count_distinct
    description: Count of unique records
  dimensions:
  - name: product_category_name
    sql: product_category_name
    type: string
    description: Product Category Name dimension
    primary_key: true
  - name: product_category_name_english
    sql: product_category_name_english
    type: string
    description: Product Category Name English dimension
