views:
- name: business_metrics
  description: Key business metrics across all entities
  cubes:
  - join_path: orders
    includes: '*'
    prefix: true
  - join_path: order_items
    includes: '*'
    prefix: true
  - join_path: products
    includes: '*'
    prefix: true
